package us.ihmc.alexMocap;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;

import us.ihmc.alexMocap.calibration.RobotCaptures;
import us.ihmc.alexMocap.core.CsvEncoderLog;
import us.ihmc.alexMocap.core.EncoderSample;
import us.ihmc.alexMocap.mocap.MocapFrameRecorder;

/**
 * <b>Run this one file to see the whole thing, ending in the SCS2 window.</b>
 * <p>
 * Green-arrow it in IntelliJ. It generates a leg-only marker set on the real Alex model, writes the
 * capture out as CSV, calibrates it, replays it, and opens the visualizer.
 * </p>
 *
 * <pre>
 * AlexLegDemo                       generate, calibrate, replay, then open SCS2
 * AlexLegDemo --no-visualize        the same without the window (works headless / over SSH)
 * AlexLegDemo --degenerate          the hip-X-only marker set: a perfect-looking, 57 mm-wrong fit
 * AlexLegDemo --out /some/dir       write somewhere other than build/alex-demo
 * </pre>
 *
 * <h2>Why this lives in test scope</h2>
 * <p>
 * It depends on {@link RobotCaptures}, which invents mocap data. That belongs nowhere near the
 * shipping jar -- a synthetic-capture generator on the production classpath is an invitation to
 * calibrate against made-up markers by accident. IntelliJ runs a {@code main} out of test sources
 * without complaint, so nothing is lost by keeping it here.
 * </p>
 *
 * <h2>What it does NOT do</h2>
 * <p>
 * Nothing here touches hardware or a camera. The marker positions are generated by forward
 * kinematics from the URDF and then given Gaussian noise, so this demonstrates that <b>the code
 * recovers an answer it was given</b> -- not that Alex's real geometry is good enough. That
 * distinction is the whole of PR_PLAN.md's "be honest about what this proves", and it does not stop
 * being true because the URDF is now the real one.
 * </p>
 */
public class AlexLegDemo
{
   /** FRAMEWORK.md §17's target for a tight volume at the gantry. */
   private static final double SIGMA = 0.3e-3;

   /** Enough for the A′ loop to be well determined; §17 asks for ≥ 30. */
   private static final int CAPTURES = 60;

   public static void main(String[] args) throws Exception
   {
      boolean visualize = !List.of(args).contains("--no-visualize");
      boolean degenerate = List.of(args).contains("--degenerate");
      Path outputDirectory = Path.of(argumentValue(args, "--out", "build/alex-demo")).toAbsolutePath();

      Files.createDirectories(outputDirectory);

      String[] markedLinks = degenerate ? RobotCaptures.HIP_X_ONLY_MARKED_LINKS : RobotCaptures.PRIMARY_MARKED_LINKS;

      System.out.println("=".repeat(78));
      System.out.println("alex-mocap on the real Alex model  --  " + (degenerate ? "DEGENERATE hip-X-only set" : "leg marker set"));
      System.out.println("=".repeat(78));
      System.out.println("marked   " + String.join(", ", markedLinks));
      System.out.println("captures " + CAPTURES + " at sigma = " + 1000.0 * SIGMA + " mm");
      System.out.println("output   " + outputDirectory);
      System.out.println();

      // ---- 1. invent a capture session -------------------------------------------------------
      RobotCaptures.Options options = new RobotCaptures.Options().captures(CAPTURES)
                                                                 .noise(SIGMA)
                                                                 .randomize(RobotCaptures.LEG_JOINTS)
                                                                 .marked(markedLinks);
      if (degenerate)
         options.noise(0.0);

      RobotCaptures.Planted planted = RobotCaptures.generate(options);
      writeCaptureSession(outputDirectory, planted);

      System.out.println("[1/3] wrote capture.csv, encoders.csv, alex.urdf");
      System.out.println();

      // ---- 2. calibrate ----------------------------------------------------------------------
      System.out.println("-".repeat(78));
      System.out.println("[2/3] CalibrationRunner --calibrate");
      System.out.println("-".repeat(78));

      int calibrationExit = CalibrationRunner.run(new String[] {"--calibrate", "--input", path(outputDirectory, "capture.csv"), "--encoders",
            path(outputDirectory, "encoders.csv"), "--urdf", path(outputDirectory, "alex.urdf"), "--sigma", Double.toString(SIGMA), "--world-tilt", "0.08",
            "--output", path(outputDirectory, "calibration.json"), "--note", "AlexLegDemo"}, System.out, System.err);

      if (calibrationExit != 0)
      {
         System.err.println("Calibration exited " + calibrationExit + "; not replaying.");
         System.exit(calibrationExit);
      }

      // ---- 3. replay, and open the window ----------------------------------------------------
      System.out.println();
      System.out.println("-".repeat(78));
      System.out.println("[3/3] ReplayRunner" + (visualize ? " --visualize" : ""));
      System.out.println("-".repeat(78));

      List<String> replay = new ArrayList<>(List.of("--input",
                                                    path(outputDirectory, "capture.csv"),
                                                    "--encoders",
                                                    path(outputDirectory, "encoders.csv"),
                                                    "--urdf",
                                                    path(outputDirectory, "alex.urdf"),
                                                    "--calibration",
                                                    path(outputDirectory, "calibration.json"),
                                                    "--output-directory",
                                                    outputDirectory.toString(),
                                                    "--world-tilt",
                                                    "0.08",
                                                    "--sigma",
                                                    Double.toString(SIGMA),
                                                    "--velocity",
                                                    "--error-budget"));
      if (visualize)
         replay.add("--visualize");

      int replayExit = ReplayRunner.run(replay.toArray(new String[0]), System.out, System.err);

      System.out.println();
      System.out.println("=".repeat(78));
      System.out.println("Wrote to " + outputDirectory + ":");
      System.out.println("  calibration.json    the CalibrationResult (layouts + Delta + provenance)");
      System.out.println("  com.csv             whole-body CoM trajectory, gravity-aligned world frame");
      System.out.println("  pelvis.csv          pelvis pose trajectory. No velocity column, by design");
      System.out.println("  pelvisVelocity.csv  the offline centred-SG second pass (FRAMEWORK.md section 13)");
      System.out.println("  conditioning.csv    per-frame sigma3 and visible count, per cluster");
      System.out.println("=".repeat(78));

      // ReplayRunner exits 1 when any frame was refused. On the degenerate run that is expected and
      // is the point being made, so do not dress it up as success either way.
      System.exit(replayExit);
   }

   private static void writeCaptureSession(Path directory, RobotCaptures.Planted planted) throws Exception
   {
      try (MocapFrameRecorder recorder = new MocapFrameRecorder(directory.resolve("capture.csv"), planted.markers))
      {
         for (int k = 0; k < planted.captureSet.getCaptureCount(); k++)
            recorder.write(planted.captureSet.getCapture(k).getMocapFrame());
      }

      List<EncoderSample> encoders = new ArrayList<>();

      for (int k = 0; k < planted.captureSet.getCaptureCount(); k++)
         encoders.add(planted.captureSet.getCapture(k).getEncoderSample());

      CsvEncoderLog.write(directory.resolve("encoders.csv"), encoders);
      Files.copy(RobotCaptures.alexUrdfPath(), directory.resolve("alex.urdf"), StandardCopyOption.REPLACE_EXISTING);
   }

   private static String path(Path directory, String name)
   {
      return directory.resolve(name).toString();
   }

   private static String argumentValue(String[] args, String flag, String fallback)
   {
      for (int i = 0; i < args.length - 1; i++)
      {
         if (args[i].equals(flag))
            return args[i + 1];
      }

      return fallback;
   }
}
