package us.ihmc.alexMocap;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;

import us.ihmc.alexMocap.calibration.RobotCaptures;
import us.ihmc.alexMocap.core.CsvEncoderLog;
import us.ihmc.alexMocap.core.EncoderSample;
import us.ihmc.alexMocap.mocap.MocapFrameRecorder;
import us.ihmc.euclid.transform.RigidBodyTransform;
import us.ihmc.euclid.tuple4D.Quaternion;

/**
 * <b>Run this one file to see the whole thing, ending in the SCS2 window.</b>
 * <p>
 * Green-arrow it in IntelliJ. It generates a leg-only marker set on the real Alex model, writes the
 * capture out as CSV, calibrates it, replays it, and opens the visualizer.
 * </p>
 *
 * <pre>
 * AlexLegDemo                       generate, calibrate, replay, then open SCS2
 * AlexLegDemo --no-visualize        the same without the window (works headless / over SSH)
 * AlexLegDemo --degenerate          the hip-X-only marker set: a perfect-looking, 57 mm-wrong fit
 * AlexLegDemo --sweep 0.6           wider leg swing about the rest pose (radians, half-range)
 * AlexLegDemo --full-range          every joint across its whole URDF range, as §1 literally asks
 * AlexLegDemo --out /some/dir       write somewhere other than build/alex-demo
 * </pre>
 *
 * <h2>What it looks like, and why</h2>
 * <p>
 * The robot is drawn <b>where the markers say it was</b> -- suspended around
 * {@code (1.0, 2.0, 1.4)} for this capture set, not at the origin -- hanging from a gantry with its
 * legs swinging ±0.45 rad about the straight-legged rest pose, feet uncrossed. Around it are the 28
 * marker spheres it is being measured by, and a translucent <b>ghost</b> at the pose the mocap
 * pipeline reconstructs. Successive captures are independent draws, so the replay steps between
 * poses rather than sweeping smoothly through them.
 * </p>
 * <p>
 * {@code --full-range} restores what FRAMEWORK.md §1 literally asks for -- every joint uniform
 * across its whole URDF limit. It conditions the fit slightly better (in-sample RMS 1.910 mm against
 * 1.987 mm) and looks absurd: {@code HIP_Y} spans {@code [-150°, +45°]}, so it folds one thigh
 * against the chest while the other kicks forward.
 * </p>
 *
 * <h2>Why this lives in test scope</h2>
 * <p>
 * It depends on {@link RobotCaptures}, which invents mocap data. That belongs nowhere near the
 * shipping jar -- a synthetic-capture generator on the production classpath is an invitation to
 * calibrate against made-up markers by accident. IntelliJ runs a {@code main} out of test sources
 * without complaint, so nothing is lost by keeping it here.
 * </p>
 *
 * <h2>What it does NOT do</h2>
 * <p>
 * Nothing here touches hardware or a camera. The marker positions are generated by forward
 * kinematics from the URDF and then given Gaussian noise, so this demonstrates that <b>the code
 * recovers an answer it was given</b> -- not that Alex's real geometry is good enough. That
 * distinction is the whole of PR_PLAN.md's "be honest about what this proves", and it does not stop
 * being true because the URDF is now the real one.
 * </p>
 */
public class AlexLegDemo
{
   // The model is always the vendored alex.urdf -- byte-identical to the source, what the tests use,
   // and what CI needs nothing outside this repo to run. Its meshes are not beside it, and they no
   // longer need to be: `--mesh-dir` names the mesh roots separately, so the pinned bytes and the
   // drawn shapes are no longer a trade-off. See AlexSdkModels for where the roots come from.
   //
   // What this replaces: a hard-coded path into the Python estimator's checkout
   // (~/alex/invariant-estimation/assets/alex_with_imus.urdf). That was wrong twice -- it pointed
   // at a copy rather than at ihmc-alex-sdk, and it was an absolute path in a repository that has
   // since moved.

   /** FRAMEWORK.md §17's target for a tight volume at the gantry. */
   private static final double SIGMA = 0.3e-3;

   /** Enough for the A′ loop to be well determined; §17 asks for ≥ 30. */
   private static final int CAPTURES = 60;

   /**
    * Half-range of the leg sweep about the hanging rest pose, radians (25.8°).
    * <p>
    * Chosen from geometry, not taste: at this half-range the feet stay at least 0.733 m below the
    * pelvis over 200 draws, so the robot always reads as hanging with its legs moving. The
    * full-range alternative puts a foot 0.60 m forward and 0.18 m below the pelvis.
    * </p>
    */
   private static final double DEFAULT_SWEEP_HALF_RANGE = 0.45;

   /**
    * Feet must stay at least this far apart laterally, metres.
    * <p>
    * The rest stance is 0.240 m, so this keeps a visible gap without pinning the legs to it. Below
    * about 0.05 m the ankles visibly interpenetrate; above about 0.15 m the rejection starts
    * throwing away most of the sweep.
    * </p>
    */
   private static final double MINIMUM_FOOT_SEPARATION = 0.10;

   /**
    * How high the suspended pelvis hangs, metres.
    * <p>
    * The feet sit about 0.89 m below the pelvis at rest, so this clears the floor by roughly half a
    * metre -- a robot on a gantry, not one standing on the ground.
    * </p>
    */
   private static final double GANTRY_HEIGHT = 1.4;

   public static void main(String[] args) throws Exception
   {
      boolean visualize = !List.of(args).contains("--no-visualize");
      boolean degenerate = List.of(args).contains("--degenerate");
      Path outputDirectory = Path.of(argumentValue(args, "--out", "build/alex-demo")).toAbsolutePath();

      // How far each leg joint swings about the hanging rest pose, radians. See
      // RobotCaptures.Options.sweepHalfRangeRadians for why this is a sweep about *rest* and not a
      // narrowed sweep about the range midpoint -- on Alex the midpoint is a deep tuck.
      double sweep = Double.parseDouble(argumentValue(args, "--sweep", Double.toString(DEFAULT_SWEEP_HALF_RANGE)));

      if (!(sweep > 0.0) || sweep > Math.PI)
         throw new IllegalArgumentException("--sweep is a half-range in radians and must be in (0, π], was " + sweep + ".");

      // The old behaviour: every joint drawn uniformly across its whole URDF range. It is what
      // FRAMEWORK.md §1 literally asks for and it conditions the fit best, but it puts the robot in
      // postures no operator would command -- a foot 0.60 m forward and 0.18 m below the pelvis.
      boolean fullRange = List.of(args).contains("--full-range");

      Files.createDirectories(outputDirectory);

      String[] markedLinks = degenerate ? RobotCaptures.HIP_X_ONLY_MARKED_LINKS : RobotCaptures.PRIMARY_MARKED_LINKS;

      System.out.println("=".repeat(78));
      System.out.println("alex-mocap on the real Alex model  --  " + (degenerate ? "DEGENERATE hip-X-only set" : "leg marker set"));
      System.out.println("=".repeat(78));
      System.out.println("marked   " + String.join(", ", markedLinks));
      System.out.println("captures " + CAPTURES + " at sigma = " + 1000.0 * SIGMA + " mm");
      System.out.println("sweep    " + (fullRange ? "full URDF range per joint (FRAMEWORK.md section 1; postures no operator would command)"
            : String.format("+-%.2f rad (%.0f deg) about the hanging rest pose", sweep, Math.toDegrees(sweep))));
      System.out.println("output   " + outputDirectory);
      System.out.println();

      // ---- 1. invent a capture session -------------------------------------------------------
      RobotCaptures.Options options = new RobotCaptures.Options().captures(CAPTURES)
                                                                 .noise(SIGMA)
                                                                 .randomize(RobotCaptures.LEG_JOINTS)
                                                                 .marked(markedLinks);
      // Hang the robot directly above the origin triad rather than at RobotCaptures' default
      // (1.0, 2.0, 1.4), which puts it off in the corner of the view. The gantry HEIGHT is kept:
      // a robot mistakenly drawn at identity would sit at z = 0, so the placement fault this demo
      // exposed once already would still be obvious here.
      options.basePosition(0.0, 0.0, GANTRY_HEIGHT);

      if (!fullRange)
         options.sweepAboutRest(sweep).uncrossedLegs(MINIMUM_FOOT_SEPARATION);
      if (degenerate)
         options.noise(0.0);

      RobotCaptures.Planted planted = RobotCaptures.generate(options);
      writeCaptureSession(outputDirectory, planted);

      Path modelUrdf = outputDirectory.resolve("alex.urdf");
      List<String> meshDirectories = AlexSdkModels.meshResourceDirectories();

      System.out.println("[1/3] wrote capture.csv, encoders.csv, alex.urdf");
      System.out.println("      model    " + modelUrdf);

      if (visualize)
         System.out.println("      " + AlexSdkModels.describe());

      System.out.println();

      // ---- 2. calibrate ----------------------------------------------------------------------
      System.out.println("-".repeat(78));
      System.out.println("[2/3] CalibrationRunner --calibrate");
      System.out.println("-".repeat(78));

      int calibrationExit = CalibrationRunner.run(new String[] {"--calibrate", "--input", path(outputDirectory, "capture.csv"), "--encoders",
            path(outputDirectory, "encoders.csv"), "--urdf", modelUrdf.toString(), "--sigma", Double.toString(SIGMA), "--world-tilt", "0.08",
            "--output", path(outputDirectory, "calibration.json"), "--note", "AlexLegDemo"}, System.out, System.err);

      if (calibrationExit != 0)
      {
         System.err.println("Calibration exited " + calibrationExit + "; not replaying.");
         System.exit(calibrationExit);
      }

      // ---- 3. replay, and open the window ----------------------------------------------------
      System.out.println();
      System.out.println("-".repeat(78));
      System.out.println("[3/3] ReplayRunner" + (visualize ? " --visualize" : ""));
      System.out.println("-".repeat(78));

      List<String> replay = new ArrayList<>(List.of("--input",
                                                    path(outputDirectory, "capture.csv"),
                                                    "--encoders",
                                                    path(outputDirectory, "encoders.csv"),
                                                    "--urdf",
                                                    modelUrdf.toString(),
                                                    "--calibration",
                                                    path(outputDirectory, "calibration.json"),
                                                    "--output-directory",
                                                    outputDirectory.toString(),
                                                    "--world-tilt",
                                                    "0.08",
                                                    "--sigma",
                                                    Double.toString(SIGMA),
                                                    "--velocity",
                                                    "--error-budget"));
      if (visualize)
      {
         replay.add("--visualize");
         replay.add("--truth-base");
         replay.add(path(outputDirectory, "truthBase.csv"));

         for (String meshDirectory : meshDirectories)
         {
            replay.add("--mesh-dir");
            replay.add(meshDirectory);
         }

         System.out.println("The SCS2 window will open once the replay finishes, and this console will");
         System.out.println("resume when you close it. Press play if the trajectory has already run through.");
         System.out.println();
      }

      int replayExit = ReplayRunner.run(replay.toArray(new String[0]), System.out, System.err);

      System.out.println();
      System.out.println("=".repeat(78));
      System.out.println("Wrote to " + outputDirectory + ":");
      System.out.println("  calibration.json    the CalibrationResult (layouts + Delta + provenance)");
      System.out.println("  com.csv             whole-body CoM trajectory, gravity-aligned world frame");
      System.out.println("  pelvis.csv          pelvis pose trajectory. No velocity column, by design");
      System.out.println("  pelvisVelocity.csv  the offline centred-SG second pass (FRAMEWORK.md section 13)");
      System.out.println("  conditioning.csv    per-frame sigma3 and visible count, per cluster");
      System.out.println("=".repeat(78));

      // ReplayRunner exits 1 when any frame was refused. On the degenerate run that is expected and
      // is the point being made, so do not dress it up as success either way.
      System.exit(replayExit);
   }


   private static void writeCaptureSession(Path directory, RobotCaptures.Planted planted) throws Exception
   {
      try (MocapFrameRecorder recorder = new MocapFrameRecorder(directory.resolve("capture.csv"), planted.markers))
      {
         for (int k = 0; k < planted.captureSet.getCaptureCount(); k++)
            recorder.write(planted.captureSet.getCapture(k).getMocapFrame());
      }

      List<EncoderSample> encoders = new ArrayList<>();

      for (int k = 0; k < planted.captureSet.getCaptureCount(); k++)
         encoders.add(planted.captureSet.getCapture(k).getEncoderSample());

      CsvEncoderLog.write(directory.resolve("encoders.csv"), encoders);
      Files.copy(RobotCaptures.alexUrdfPath(), directory.resolve("alex.urdf"), StandardCopyOption.REPLACE_EXISTING);

      // The planted base poses, for the ghost overlay. This is TRUTH, and it exists only because
      // the session is synthetic -- ReplayRunner treats it as optional debug input and draws no
      // ghost without it, because a replay of real captures has nothing to put here.
      List<String> lines = new ArrayList<>();
      lines.add("# alex-mocap planted base poses ^Wg T_b -- TRUTH, synthetic sessions only");
      lines.add("timestamp_ns,x,y,z,qx,qy,qz,qs");

      for (int k = 0; k < planted.basePoses.length; k++)
      {
         RigidBodyTransform pose = planted.basePoses[k];
         Quaternion q = new Quaternion(pose.getRotation());
         lines.add(String.format("%d,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g,%.17g",
                                 planted.captureSet.getCapture(k).getMocapFrame().getTimestampNanoseconds(),
                                 pose.getTranslationX(),
                                 pose.getTranslationY(),
                                 pose.getTranslationZ(),
                                 q.getX(),
                                 q.getY(),
                                 q.getZ(),
                                 q.getS()));
      }

      Files.write(directory.resolve("truthBase.csv"), lines);
   }

   private static String path(Path directory, String name)
   {
      return directory.resolve(name).toString();
   }

   private static String argumentValue(String[] args, String flag, String fallback)
   {
      for (int i = 0; i < args.length - 1; i++)
      {
         if (args[i].equals(flag))
            return args[i + 1];
      }

      return fallback;
   }
}
